apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: bkimcr25x7z.azurecr.io/backend-im:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /app
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: shared-data
        emptyDir: {}